### ISSUE TITLE
all branches removed, even on first execution, sometimes?

### ISSUE THREAD

**Issue by ericb-summit** [vito/git-branches-resource#3]
We're running latest concourse, and find that often on first execution of the resource it finds all the branches, but then sometimes immediately, or on subsequent runs, considers them all removed.  Once the resource decides the branches are removed, they never come back.  Even though they still exist in git.

The reason my issue description lacks all details is that this only happens with the image of the resource found on docker hub, built 5 years ago.  As soon as I checked out the code and did a docker build in order to try to debug this,  the problem no longer reproduces at all.  Clearly something is different in the base image from 5 years ago to today.

I defer to your expertise on how to handle this.

**Comment by vito** [comment]
Sorry, not sure what's going on there but this resource was just an experiment and I don't intend to support it or encourage its use. It should become useless hopefully soon as we get to the last parts of the [v10 roadmap](https://github.com/concourse/concourse#the-road-to-concourse-v10). I'm going to archive this repo now - if you still need this functionality I would recommend forking.
